CREATE TABLE project_membership (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT      NOT NULL REFERENCES project (id),
    user_id    BIGINT      NOT NULL REFERENCES app_user (id),
    role       VARCHAR(16) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_project_membership UNIQUE (project_id, user_id)
);
CREATE INDEX idx_project_membership_project ON project_membership (project_id);
CREATE INDEX idx_project_membership_user ON project_membership (user_id);
