CREATE TABLE perf_run (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT       NOT NULL REFERENCES project (id),
    branch         VARCHAR(255),
    flag           VARCHAR(255) NOT NULL DEFAULT 'default',
    commit_sha     VARCHAR(255),
    build_url      VARCHAR(1024),
    ci_provider    VARCHAR(255),
    run_key        VARCHAR(255),
    format         VARCHAR(16)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    sample_count   BIGINT           NOT NULL DEFAULT 0,
    error_count    BIGINT           NOT NULL DEFAULT 0,
    error_pct      DOUBLE PRECISION NOT NULL DEFAULT 0,
    throughput_rps DOUBLE PRECISION NOT NULL DEFAULT 0,
    duration_ms    BIGINT           NOT NULL DEFAULT 0,
    mean_ms        DOUBLE PRECISION NOT NULL DEFAULT 0,
    p50_ms         DOUBLE PRECISION NOT NULL DEFAULT 0,
    p90_ms         DOUBLE PRECISION NOT NULL DEFAULT 0,
    p95_ms         DOUBLE PRECISION NOT NULL DEFAULT 0,
    p99_ms         DOUBLE PRECISION NOT NULL DEFAULT 0,
    min_ms         DOUBLE PRECISION NOT NULL DEFAULT 0,
    max_ms         DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX idx_perf_run_project ON perf_run (project_id, created_at);

CREATE TABLE perf_transaction (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perf_run_id  BIGINT           NOT NULL REFERENCES perf_run (id),
    label        VARCHAR(512)     NOT NULL,
    sample_count BIGINT           NOT NULL DEFAULT 0,
    error_count  BIGINT           NOT NULL DEFAULT 0,
    error_pct    DOUBLE PRECISION NOT NULL DEFAULT 0,
    mean_ms      DOUBLE PRECISION NOT NULL DEFAULT 0,
    p50_ms       DOUBLE PRECISION NOT NULL DEFAULT 0,
    p90_ms       DOUBLE PRECISION NOT NULL DEFAULT 0,
    p95_ms       DOUBLE PRECISION NOT NULL DEFAULT 0,
    p99_ms       DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX idx_perf_transaction_run ON perf_transaction (perf_run_id);
