-- Test ownership: map test classes to an owner (team/handle) by pattern, to attribute
-- failures and flakes. Lower priority wins; first match assigns the owner.
CREATE TABLE test_owner_rule (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT        NOT NULL REFERENCES project (id),
    owner      VARCHAR(255)  NOT NULL,
    pattern    VARCHAR(2000) NOT NULL,
    priority   INT           NOT NULL DEFAULT 100,
    created_at TIMESTAMP     NOT NULL
);
CREATE INDEX idx_test_owner_rule_project ON test_owner_rule (project_id);
