-- Public, revocable share links to a single run. The token (SHA-256 hashed here) is the
-- capability: anyone holding it gets a read-only view regardless of project visibility.
CREATE TABLE share_link (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT       NOT NULL REFERENCES test_run (id),
    token_hash   VARCHAR(255) NOT NULL UNIQUE,
    prefix       VARCHAR(64)  NOT NULL,
    created_by   BIGINT       REFERENCES app_user (id),
    created_at   TIMESTAMP    NOT NULL,
    last_used_at TIMESTAMP,
    revoked      BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_share_link_run ON share_link (run_id);
