-- Append-only audit trail for state-changing actions (today: AI/MCP write tools). Every
-- machine-driven mutation records who acted, what they did, on which project, and how.
CREATE TABLE audit_entry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor      VARCHAR(255),
    action     VARCHAR(64)   NOT NULL,
    source     VARCHAR(32)   NOT NULL,
    project_id BIGINT,
    detail     VARCHAR(1024),
    created_at TIMESTAMP     NOT NULL
);
CREATE INDEX idx_audit_entry_project ON audit_entry (project_id, created_at);
