CREATE TABLE project (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    repo_url   VARCHAR(1024),
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE test_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT       NOT NULL REFERENCES project (id),
    branch              VARCHAR(255),
    commit_sha          VARCHAR(255),
    build_url           VARCHAR(1024),
    ci_provider         VARCHAR(255),
    created_at          TIMESTAMP    NOT NULL,
    total_tests         INT          NOT NULL DEFAULT 0,
    passed              INT          NOT NULL DEFAULT 0,
    failed              INT          NOT NULL DEFAULT 0,
    errors              INT          NOT NULL DEFAULT 0,
    skipped             INT          NOT NULL DEFAULT 0,
    duration_ms         BIGINT       NOT NULL DEFAULT 0,
    status              VARCHAR(32)  NOT NULL DEFAULT 'PASSED',
    line_coverage_pct   DOUBLE PRECISION,
    branch_coverage_pct DOUBLE PRECISION
);
CREATE INDEX idx_test_run_project_created ON test_run (project_id, created_at);

CREATE TABLE test_suite_result (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      BIGINT       NOT NULL REFERENCES test_run (id),
    name        VARCHAR(512) NOT NULL,
    tests       INT          NOT NULL DEFAULT 0,
    failures    INT          NOT NULL DEFAULT 0,
    errors      INT          NOT NULL DEFAULT 0,
    skipped     INT          NOT NULL DEFAULT 0,
    duration_ms BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX idx_suite_run ON test_suite_result (run_id);

CREATE TABLE test_case_result (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id             BIGINT       NOT NULL REFERENCES test_run (id),
    suite_name         VARCHAR(512),
    class_name         VARCHAR(512),
    name               VARCHAR(512) NOT NULL,
    status             VARCHAR(16)  NOT NULL,
    duration_ms        BIGINT       NOT NULL DEFAULT 0,
    failure_type       VARCHAR(512),
    failure_message    VARCHAR(2000),
    failure_stacktrace TEXT
);
CREATE INDEX idx_case_run ON test_case_result (run_id);
CREATE INDEX idx_case_run_status ON test_case_result (run_id, status);

CREATE TABLE coverage_report (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              BIGINT NOT NULL UNIQUE REFERENCES test_run (id),
    line_covered        INT    NOT NULL DEFAULT 0,
    line_missed         INT    NOT NULL DEFAULT 0,
    branch_covered      INT    NOT NULL DEFAULT 0,
    branch_missed       INT    NOT NULL DEFAULT 0,
    instruction_covered INT    NOT NULL DEFAULT 0,
    instruction_missed  INT    NOT NULL DEFAULT 0,
    method_covered      INT    NOT NULL DEFAULT 0,
    method_missed       INT    NOT NULL DEFAULT 0
);

CREATE TABLE coverage_file_entry (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id      BIGINT       NOT NULL REFERENCES coverage_report (id),
    package_name   VARCHAR(512),
    file_name      VARCHAR(512) NOT NULL,
    line_covered   INT          NOT NULL DEFAULT 0,
    line_missed    INT          NOT NULL DEFAULT 0,
    branch_covered INT          NOT NULL DEFAULT 0,
    branch_missed  INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_cov_file_report ON coverage_file_entry (report_id);
