-- Per-project alert channels (#240). Multi-tenant by project: each project routes its alerts
-- to its own targets, unlike a single global channel list. The credential is stored encrypted
-- at rest by the application (the `secret` column never holds plaintext).
CREATE TABLE alert_channel (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL REFERENCES project (id),
    type       VARCHAR(16)  NOT NULL,
    label      VARCHAR(255) NOT NULL,
    target     VARCHAR(1024),
    secret     VARCHAR(2048),
    tags       VARCHAR(255),
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_alert_channel_project ON alert_channel (project_id);
