-- Ingest processing history (#368): one row per upload attempt — what was ingested, its
-- outcome, and the failure reason if it failed. Written out-of-band (its own transaction) so a
-- failed, rolled-back ingest still leaves a record operators can review.
CREATE TABLE ingest_job (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status         VARCHAR(16)  NOT NULL,
    project_name   VARCHAR(255),
    branch         VARCHAR(255),
    commit_sha     VARCHAR(64),
    kind           VARCHAR(32),
    size_bytes     BIGINT,
    uploader       VARCHAR(255),
    created_at     TIMESTAMP    NOT NULL,
    finished_at    TIMESTAMP,
    duration_ms    BIGINT,
    failure_reason VARCHAR(2048),
    run_id         BIGINT,
    perf_run_id    BIGINT,
    project_id     BIGINT
);
CREATE INDEX idx_ingest_job_created ON ingest_job (created_at DESC);
