CREATE TABLE flaky_test (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT       NOT NULL REFERENCES project (id),
    class_name VARCHAR(512),
    name       VARCHAR(512) NOT NULL,
    status     VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    note       VARCHAR(1000),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_flaky_test UNIQUE (project_id, class_name, name)
);
CREATE INDEX idx_flaky_test_project ON flaky_test (project_id);
