CREATE TABLE triage_rule (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT        NOT NULL REFERENCES project (id),
    name       VARCHAR(255)  NOT NULL,
    category   VARCHAR(255)  NOT NULL,
    pattern    VARCHAR(2000) NOT NULL,
    priority   INT           NOT NULL DEFAULT 100,
    enabled    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP     NOT NULL
);
CREATE INDEX idx_triage_rule_project ON triage_rule (project_id);
