CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(255),
    email         VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(16)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE api_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES app_user (id),
    name         VARCHAR(255) NOT NULL,
    token_hash   VARCHAR(255) NOT NULL UNIQUE,
    prefix       VARCHAR(64)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    expires_at   TIMESTAMP,
    last_used_at TIMESTAMP,
    revoked      BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_api_token_user ON api_token (user_id);
