CREATE TABLE project_settings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT NOT NULL UNIQUE REFERENCES project (id),
    base_branch           VARCHAR(255),
    min_line_coverage     DOUBLE PRECISION,
    max_coverage_drop_pct DOUBLE PRECISION,
    fail_on_new_failures  BOOLEAN
);
CREATE INDEX idx_project_settings_project ON project_settings (project_id);
