{{- if .Values.ingress.enabled }}
{{- $fullName := include "unitrack.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $path := .Values.ingress.path -}}
{{- $pathType := .Values.ingress.pathType -}}
{{- $hosts := prepend (.Values.ingress.extraHosts | default list) .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "unitrack.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if $.Values.ingress.tlsSecretName }}
      secretName: {{ $.Values.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}
