name: gradle-plugin
on:
  - push
  - manual
push:
  branches:
    - main
  paths:
    - unitrack-gradle-plugin/**
    - unitrack-cli/**
    - .builder/pipelines/gradle-plugin.yml
checkout: true
jobs:
  build:
    image: eclipse-temurin:21-jdk
    timeout: 30m
    cache:
      key: gradle-unitrack
      paths:
        - .m2/repository
        - .gradle
    steps:
      - name: install-cli-to-local-repo
        run: ./mvnw -B -ntp -pl unitrack-cli -am -DskipTests install -Dmaven.repo.local=.m2/repository
      - name: build-gradle-plugin
        run: cd unitrack-gradle-plugin && ./gradlew build --no-daemon --gradle-user-home ../.gradle -Dmaven.repo.local=../.m2/repository
